"""
--- Day 2: Inventory Management System ---
"""

data = ' qysdgimlcaghpfozuwejmhrbvx qysdtiklcagnpfhzuwbjmhrtvx qysdtiflcsgnpfozuwejmhruvx qkshtiklnagnpfozuwejmhrbvx qysdtnklcagnpmozuwejmhrrvx qysdttkecagnpfozuwijmhrbvx qyedtiklcagnvfozuweymhrbvx qyzdtikzcagnpfozuwejmhqbvx qysdtiklcagnpfozlwedmhqbvx qjsdtiklcagnpfozubejmhrbvq qysdtiklcagnpfozvvejmhrbex qdsdziklcagnpfouuwejmhrbvx qysttikqccgnpfozuwejmhrbvx qysdtiklcagnpbozwwecmhrbvx qysdtiklcagnpfozuwexmmrjvx nysdtiklcqgjpfozuwejmhrbvx cysdoiqlcagnpfozuwejmhrbvx qysdthxlcagnpfozuwejmcrbvx qyswtiklcrgnpfozuwejmhrbvf qysdtiklcagnpfozurejmhvpvx qysdtiklcegnpfdzuwejghrbvx qysdtjkluagnpfozuwenmhrbvx qysdtimlcagnpjwzuwejmhrbvx qyrdtiklcegnpeozuwejmhrbvx qysdmiklcagnpfokswejmhrbvx qysdtizlcagnpiozuwecmhrbvx qysdtiklcignafxzuwejmhrbvx qycdjiklcagnpzozuwejmhrbvx qysdtiklcagnpjozuwepihrbvx qyedtiklcrgnpfozuvejmhrbvx mysdtikrcagnpfozwwejmhrbvx qysdtiklcagnpfozuhcjmhrbsx qmsdtiklcagnpfozuwehmhrevx qgsdtiklcagnpfozuwejvhrbvp lysdtikleagnpfozuwejmhrnvx qxsdtivlzagnpfozuwejmhrbvx qysdtiklcoggpfozuwebmhrbvx wysdtiklcagnpfozuwejmornvx jysdtiklvagntfozuwejmhrbvx qmsdtiklcagnpfozuwejmrrbax qysdttklcagnpfoiuwejmhrbvh qysdtnklcaenpfozupejmhrbvx qysdtoklcagnpfozuwexmhrbvq qysdtiklcagnpuoeuwejmhrjvx iysdtitncagnpfozuwejmhrbvx qysdtixrcagnprozuwejmhrbvx qyfdtiplcagnpfouuwejmhrbvx qysdtmklcagnpfowuwejmhrbox qysdtiklcagnxiozuwejphrbvx fysdtiklcagnptozuwejmhrbvo qysdqiklcagnplozuwejmhmbvx qysdtwkacagnpfosuwejmhrbvx qysdtitlcagnpfozufajmhrbvx qysdtcklcagopfdzuwejmhrbvx qmfdtdklcagnpfozuwejmhrbvx qysztiklcaonpfozuwejmhrbfx qygdtiklcggnpfozuwejmhrhvx qysdiiklcagnpfozukejmcrbvx qysdtrkloagnpfozuwujmhrbvx qycdtiklcagnpfozywejmhrlvx qgsdtikdcagnpfozgwejmhrbvx qyudtikleagvpfozuwejmhrbvx pysdtiqlcagnpfozuwejmarbvx qysdtiklcaenpfozuwehahrbvx qhsttiklcagnpfovuwejmhrbvx zysdtikqmagnpfozuwejmhrbvx rysdtikacagnpfozuwevmhrbvx zysntikllagnpfozuwejmhrbvx qysttimlcagndfozuwejmhrbvx qysdtiklcaxopfqzuwejmhrbvx qysdtislcagnpfozuwejmtrbnx qysdviklcagnpfozswejmhibvx qmsdtiklrygnpfozuwejmhrbvx qysztiklcagnpfozuwejmorbrx xysdtiklcagnzwozuwejmhrbvx qysjthklcagnpfozowejmhrbvx qysdtiklcagnpfofxwemmhrbvx jysdtiklcagnpfozfwehmhrbvx qysdtgklaagnpfozhwejmhrbvx qqsdtiklcaenpfozuwejmhrvvx qysdtikloajppfozuwejmhrbvx qysdtiklcagnpwozuwejmhrhsx qpsdtiklcapnprozuwejmhrbvx qyzdtiklcagnpcozuwejmhrbvc qusdhiklcagnpfozuwejmhrbxx qysdtiklcagnpfozqwejthrvvx qysvtiklcagnpfoiuwedmhrbvx qgsdtiklcagvpfozuwejmhrbvf qysdtikxcawnpfozuwejmarbvx qyvctiklcaynpfozuwejmhrbvx qyyltiklnagnpfozuwejmhrbvx oysdtillcagnpfozuwejmnrbvx qysdtiklcagnpfozuvmjmhrbzx qykdtikocagnpfhzuwejmhrbvx qysdtvkloagnpfozuwejmkrbvx qysetiklcagnpfozuwejmhrxvh qysdtiklcavnpfuzuwejmhrbvh qmndtiklcagnpfojuwejmhrbvx qysdtialcagnpfozuwejmdrqvx qysdtiklcagnpfozuwejtzrbvv qysdtiklxagnpyozufejmhrbvx qysdtiklcagnpfgzewejahrbvx qysdtiklcagppsozuwejmhrdvx qykdtiklcainpfozuwejqhrbvx qysdtiklcagnpfszxwejmhubvx qyrdtiklcagkptozuwejmhrbvx qysdsiklcagnpfozsvejmhrbvx qypdtiklcagypfozuwejmhrlvx qssdtiklcagnpfozuwqjmirbvx qyshtiklcagnpfrzuwyjmhrbvx qysdtiklcagnpfqzuwenmgrbvx qysdtiklcagnpfonuwejmhkwvx qysdhiklcagnpfokuwejmhrfvx jysrtiklcaenpfozuwejmhrbvx qysdtiilcagnpfozuwejmhcbvl qysdtiklcagnheozuwejmhrbvn qysdtikucagwpfojuwejmhrbvx qysdtinlctgnpfozuwujmhrbvx qysdtiklcagnpiozuwejmtrbjx qysktiklcagqpfozuwcjmhrbvx qysddiklcagnpfozpwejmhrbvh wysdtiplcagnpfozuwejyhrbvx qysdtiklcagnpfjzlwejmhrcvx qysdtikleagopbozuwejmhrbvx qysdtqklcwgnpfozuwejmirbvx qysdtiklcugnpmozuwejmhrbvp qysdtiklcagnpfozpwejmnrbvz qysdtiklcagnpcozuwejmhbbmx uysitiklcagnpfozewejmhrbvx qykdtiklcasnpfozuwejdhrbvx qyjdtiklcagnpqozuzejmhrbvx qysdtiklcagaifozuwejmhrbvh qysdtiklcagnhfozuwyjrhrbvx qysetiklcaanpfozuwyjmhrbvx qyfdtiklcagnphozulejmhrbvx qysdtikkcrgnpfozuwejmhpbvx qysdtiklcarnpfdzuwejmhrbvq qysdtiklcfyrpfozuwejmhrbvx rysdtitlcagnpfoznwejmhrbvx qysdtiilcagnffozugejmhrbvx qysdyifloagnpfozuwejmhrbvx qysdtiklcegnpfozuwejmlrcvx qysdtiklcagnpfozuwajmhbbqx qysptrklcarnpfozuwejmhrbvx qysdtiklcagnldozuwejmhwbvx qysdtiklczgqpfozuwejmhobvx qyxdtiklcagcpfoiuwejmhrbvx qysatiklczgnpfozawejmhrbvx qysduiklcagnpfoziwejyhrbvx qysdtgklqagnpfozujejmhrbvx qysdtiqlcagnpfozzdejmhrbvx qysdtiklcngnpfofuwejmzrbvx qysdtiklcagnyfozuwejrnrbvx qysdtiplcagnpfozowmjmhrbvx qyswtiklcagnplozuwedmhrbvx qyseiiklcagnpfozuwejmhibvx qysdtiklcagnpfozutusmhrbvx qysdtimlcagnpfozccejmhrbvx qnsdniklcagnpfobuwejmhrbvx qysrtiklcagnpfofuwejmhrbyx qyzdtiklcagnpfoizwejmhrbvx qysdtjslcdgnpfozuwejmhrbvx qysdtiklcagnpxoyuwejmrrbvx qysdtikllagnpfmzuwbjmhrbvx qysdtitlcagnkfozuwejwhrbvx qymdtiklcggnpfozuwejmzrbvx qysdtiklclfnpfozuhejmhrbvx qysdtyklcagnpfozuwejmhhbix qysetiklcagnpfozuwejmhrspx qysdipklcagnpfozuwejmhrbex uysgtiklcagnpmozuwejmhrbvx qysdtiklmagnpfozuwqlmhrbvx qysdtiklcagnyfozxwejmhrmvx qysutillcagnpfozuwejmhrbbx casdtiklcagnpfopuwejmhrbvx qesdtiklctgnpfmzuwejmhrbvx qysdtiklcagopfozjwejmdrbvx jzsdtiklcagnpfozuwejmurbvx qysdtiklcjgnpfonuwejrhrbvx qysdtiklcrgnpnozuwejmhqbvx oyhdtiklcagnpfozuwekmhrbvx qysstiklcagjpfozuwejmhrbnx qyudtiklsagnpsozuwejmhrbvx qysdtiilcagnpfozusejmhrbva qysdtiklcaknpfozmwejmhgbvx qysdbiklcpgnpfozuwejmrrbvx qybdtiklcagvpfokuwejmhrbvx qysatiklcagnpwofuwejmhrbvx qysdtiklcadnpfonuwejmcrbvx qysdtijfcagnpfozuvejmhrbvx qysdtiklcagnpfhluuejmhrbvx qysdtiklcagnpfoguwejqhrwvx qlsdtiklcagnpfojuwehmhrbvx qyhdtiolcagnpfozuwejmhrzvx qmsdtiklcagnppozuwpjmhrbvx qysdtiklvvgnpfvzuwejmhrbvx qysdtiklcagnpfszuwajmhrcvx qysdtiklcagnpfmzuwekmhrbyx qysdtiklcagwpfozumevmhrbvx qysdtaklcagnpfozuwejvhzbvx qysotiklcagntffzuwejmhrbvx qysdtiklcagnpfowuweqmhrivx qysdtrkloagnxfozuwujmhrbvx qasdiiklcagnpfozuwegmhrbvx qysbtiklcagnpfozuwejthrbhx hysdtikllagnpfozuwejmhrbbx qyqdtiklcagnpsozuwejmcrbvx qysdtiklcagnpiqzuwejmhrbux qnsdtiklcagnpfozdwejmhbbvx qysjbiklcagzpfozuwejmhrbvx qysdtiklcagnpfifuwejmhrbvg qysdtiklcaggpkozunejmhrbvx qxsdtiklcavnpfozuwfjmhrbvx qysdtikycabnpfkzuwejmhrbvx qyswtzklcagnpfozuwejmhrlvx qysdtikqcagnpfozuwejrhnbvx qysdtiplaagnpfozuwejmhruvx qjcdtiklcagnpfozujejmhrbvx nysdtyklcagnpfozutejmhrbvx qysrtiklcagnpfnzuwejmhrbdx zysdtielcagnpfozuwezmhrbvx qysdtikpvagnpfozuzejmhrbvx qysdwiklcagnpfozueejmhrlvx dysdmiklcagnpfozuwejzhrbvx qysdtiklcjgnpfozuweimhmbvx qysdtiklciynpyozuwejmhrbvx qksdtiklcagnpbozubejmhrbvx qysdtiklkagnpfozuwejmhrjvb yyxdtiklcagnpfomuwejmhrbvx qysdtiklcagnfnozuwejmhrbvv qysdtzklcagnpfozuwejmhrmvb qysduiklclgnpfozuwejmhrbvn qyndtmklcavnpfozuwejmhrbvx qisdkiklcagnpfozuwqjmhrbvx qysdtrkycagypfozuwejmhrbvx qhsdtiklcwgnmfozuwejmhrbvx qysdaiklcannpfozupejmhrbvx zysdtiklcagnpjozuwejmhrbwx qysdtikxcagnpfozuwejmcrxvx qysdtzklcagnpfozewejmhrbvk qysdwtklcagnhfozuwejmhrbvx qysdtqklcaenpfozuwejmdrbvx qysdtiklcagnpfozuoeemhqbvx nysdtikocagnpfozuwejmhwbvx qysxtiklcagnpfozqwejmhrbax qysdtielcasnpfozuwejmhsbvx qysdtiklcaknpfozuwejcwrbvx qysytiklcagnpfozdfejmhrbvx qysdtiklcagmpfozuwejmgrbox qysdtielcagnpfpzuwejhhrbvx'
IDs = [string.strip() for string in data.split()]


def find_same_ids():
    two = three = bool()
    occurs = dict(two=0, three=0)

    for s in IDs:
        for l in s:
            if not two and s.count(l) == 2:
                two = True
            if not three and s.count(l) == 3:
                three = True
            if two and three:
                break

        occurs['two'] += two
        occurs['three'] += three
        two = three = bool()

    print(occurs['two'] * occurs['three'])


def find_small_difference():
    import itertools

    result = str()
    for s1, s2 in itertools.combinations(IDs, 2):
        diffs = [i for i in range(len(s1)) if s1[i] != s2[i]]
        if len(diffs) == 1:
            for l in s1:
                if s1.index(l) not in diffs:
                    result += l
    print(result)
